---
title: "Quienes somos"
author: "Una imagen"
date: "3/5/2020"
output: html_document
---

```{r}
library(here)
```


Bienvenidos a "Una imagen". Nuestro objetivo es hacer visible información sobre Uruguay, de forma que sea fácilmente interpretable. Trabajamos en [R](https://www.r-project.org/) utilizando la interfase [RStudio](https://rstudio.com/). Tenemos un [código de conducta](https://github.com/UnaImagen/UnaImagen/blob/master/CODE_OF_CONDUCT.md) que rije nuestro trabajo y el relacionamiento con los colaboradores.

Todos los códigos están disponibles en el repositorio de ["Una imagen"](https://github.com/UnaImagen/UnaImagen) en Github, para ser visualizados y adaptados.

Este es un repositorio abierto. Si quieres colaborar con nosotros, eres bienvenido o bienvenida! [Aquí](https://github.com/UnaImagen/UnaImagen/blob/master/CONTRIBUTING.md) puedes encontrar una guía de como colaborar con el Proyecto "Una imagen".

Una imagen es:

**Lucila Bonilla** (agregar foto y breve CV)

**Daniel Czarnievicz** (agregar foto y breve CV)

**Iael Klaczo** (agregar foto y breve CV)

**Paula Pereda**


**Leandro Zipitría** 

Leandro es Doctor en Economía. Está afiliado al Departamento de Economía, Facultad de Ciencias Sociales, UdelaR. Trabaja principalmente en temas de regulacion, organización industrial y defensa de la competencia. Es investigador Nivel I por la ANII. Su página web está disponible [aquí](https://leandro-zipitria.com/).

