---
title: "Construcción en Montevideo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: "https://github.com/daczarne/UnaImagen/tree/master/DataBases/Construccion"
runtime: shiny
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css">

```{r global, include=FALSE}
library(flexdashboard, quietly = TRUE)
library(plotly, quietly = TRUE)
library(shiny, quietly = TRUE)
construccion <- readr::read_rds(path = here::here("/DataBases/Construccion/app/construccion.rds"))
```

```{r variables_globales}
## Formato numérico
big_mark <- "."
decimal_mark <- ","
digits_permisos <- 0L

## Value Boxes
valuebox_color <- "#0570b0"
valuebox_icon_total <- "fas fa-hammer"
valuebox_icon_vivienda <- "fas fa-home"
valuebox_icon_comeindu <- "fas fa-industry"
valuebox_icon_otros <- "fas fa-building"
```

```{r reactive_functions}
## Devuelve la cantidad total de permisos en el año seleccionado por el usuario
total <- reactive({
   construccion %>% 
      dplyr::group_by(
         year
      ) %>% 
      dplyr::summarise(
         permisos = sum(permisos)
      ) %>% 
      dplyr::filter(
         year == input$year
      ) %>% 
      dplyr::pull()
})

## Devuelve la cantidad de permisos con destino vivienda en el año seleccionado por el usuario
vivienda <- reactive({
   construccion %>% 
      dplyr::group_by(
         year,
         destino
      ) %>% 
      dplyr::summarise(
         permisos = sum(permisos)
      ) %>% 
      dplyr::filter(
         year == input$year,
         destino == "Vivienda"
      ) %>% 
      dplyr::pull(
         permisos
      )
})

## Devuelve la cantidad de permisos con destino comercio en el año seleccionado por el usuario
comercio <- reactive({
   construccion %>% 
      dplyr::group_by(
         year,
         destino
      ) %>% 
      dplyr::summarise(
         permisos = sum(permisos)
      ) %>% 
      dplyr::filter(
         year == input$year,
         destino == "Comercio"
      ) %>% 
      dplyr::pull(
         permisos
      )
})

## Devuelve la cantidad de permisos con destino industria en el año seleccionado por el usuario
industria <- reactive({
   construccion %>% 
      dplyr::group_by(
         year,
         destino
      ) %>% 
      dplyr::summarise(
         permisos = sum(permisos)
      ) %>% 
      dplyr::filter(
         year == input$year,
         destino == "Industria"
      ) %>% 
      dplyr::pull(
         permisos
      )
})

```

Column {.sidebar}
-----------------------------------------------------------------------

Cantidad de permisos de construcción emitidos por la IMM. Los datos se muestran con apertura por Tipo de permiso y destino del inmueble. El Tipo IPH equivale a Incorporación a Propiedad Horizontal. Fuente: Instituo Nacional de Estadística.

```{r}
selectInput(
   inputId = "year",
   label = "Seleccione un año",
   selected = max(construccion$year),
   choices = sort(unique(construccion$year), decreasing = TRUE)
)
```

Row {data-width=100}
-----------------------------------------------------------------------

### Total de permisos

```{r}
renderValueBox({
   valueBox(
      value = formattable::comma(
         x = total(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_total,
      color = valuebox_color
   )
})
```

### Vivienda

```{r}
renderValueBox({
   valueBox(
      value = formattable::comma(
         x = vivienda(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_vivienda,
      color = valuebox_color
   )
})
```

### Comercio e Industria

```{r}
renderValueBox({
   valueBox(
      value = formattable::comma(
         x = comercio() + industria(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_comeindu,
      color = valuebox_color
   )
})
```

### Otros/Varios

```{r}
renderValueBox({
   valueBox(
      value = formattable::comma(
         x = total() - vivienda() - comercio() - industria(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_otros,
      color = valuebox_color
   )
})
```


Row {data-width=450}
-----------------------------------------------------------------------

### Permisos por tipo y destino

```{r}
renderPlotly({
   construccion %>% 
   dplyr::filter(
      year == input$year
   ) %>% 
   dplyr::mutate(
      proporcion = permisos / sum(permisos) * 100
   ) %>% 
   plotly::plot_ly() %>% 
   plotly::add_trace(
      x = ~destino,
      y = ~tipo,
      type = "scatter",
      mode = "markers",
      marker = list(
         size = ~proporcion
      ),
      hovertemplate = ~paste0(
         "<b>Tipo</b>: %{y}",
         "<br>",
         "<b>Destino</b>: %{x}",
         "<br>",
         "<b>Permisos</b>: ",
         formattable::comma(
            x = permisos,
            digits = digits_permisos,
            big.mark = big_mark,
            decimal.mark = decimal_mark
         )
      ),
      name = " "
   ) %>% 
   plotly::layout(
      xaxis = list(
         title = "<b>Destino</b>"
      ),
      yaxis = list(
         title = "<b>Tipo</b>"
      )
   ) %>% 
   plotly::config(
      locale = "es",
      displayModeBar = FALSE
   )
})
```

