---
title: Juntos o separados
author: Leandro Zipitria
date: '2020-03-10'
slug: juntos-o-separados
categories: []
tags:
  - economía
  - población
keywords:
  - tech
---

<!--more-->


Densidad poblacional (población por kilómetro cuadrado) según zona censal. En base al Censo 2011 de población del INE.


```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

library(rgdal)
library(dplyr)
library(leaflet)
library(sf)
library(RColorBrewer)


ShapeCenso2011 <- read_sf(here::here("./DataBases/Censo2011/ShapeCenso2011.shp"))

```

```{r mapadensidadpoblacional, echo=FALSE, warning=FALSE, message=FALSE, fig.height = 8, fig.width = 10}


#### ----------------- Grafico -----------------


cuts <- quantile(ShapeCenso2011$personaskm, probs = seq(0,1, by=0.1))
#display.brewer.all()
pal <- colorBin("RdYlBu", domain = ShapeCenso2011$personaskm, bins = cuts, reverse = T)


leaflet(ShapeCenso2011) %>%
   addTiles() %>%
   setView(-56.1, -32, zoom = 7)  %>%
   addPolygons(
      fillColor = ~pal(personaskm),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7,
      highlight = highlightOptions(
         weight = 5,
         color = "#666",
         dashArray = "",
         fillOpacity = 0.7,
         bringToFront = TRUE),
      label = ~personaskm,
      labelOptions = labelOptions(
         style = list("font-weight" = "normal", padding = "3px 8px"),
         textsize = "15px",
         direction = "auto")) %>%
   addLegend(pal = pal, values = ~pob, opacity = 0.7, title = NULL,
             position = "bottomright")

```

Fuente: elaborado en base al Censo 2011 del INE.