---
title: Ingresos en 2018
author: Leandro Zipitria
date: '2020-03-12'
slug: ingresos-en-2018
categories: []
tags:
  - ingresos
  - uruguay
keywords:
  - tech
---

Ingresos promedio en dólares del año 2018, por departamento y barrio para Montevideo.

<!--more-->

Ingresos promedio en dólares del año 2018, por departamento y barrio para Montevideo. 

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
   echo = FALSE,
   message = FALSE,
   warning = FALSE,
   eval = TRUE,
   error = FALSE
)
library(magrittr, quietly = TRUE)
```

```{r carga_datos}
mapa <- sf::read_sf(here::here("./DataBases/ECH/2018/ShapeECH2018.shp"))
pal <- leaflet::colorNumeric(palette = "Blues", domain = mapa$ingUSD)
```

```{r mapa_ingresos, fig.height = 8, fig.width = 10}
leaflet::leaflet(
   data = mapa
) %>%
   leaflet::addTiles() %>%
   leaflet::setView(
      lng = -56.1,
      lat =  -32,
      zoom = 7
   ) %>% 
   leaflet::addPolygons(
      fillColor = ~pal(ingUSD),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7,
      highlight = leaflet::highlightOptions(
         weight = 5,
         color = "#666",
         dashArray = "",
         fillOpacity = 0.7,
         bringToFront = TRUE
      ),
      label = base::paste0(
         dplyr::case_when(
            stringr::str_to_sentence(mapa$NOMBRE) == "Rio negro" ~ "Río Negro",
            stringr::str_to_sentence(mapa$NOMBRE) == "Paysandu" ~ "Paysandú",
            stringr::str_to_sentence(mapa$NOMBRE) == "Tacuarembo" ~ "Tacuarembó",
            stringr::str_to_sentence(mapa$NOMBRE) == "Cerro largo" ~ "Cerro Largo",
            stringr::str_to_sentence(mapa$NOMBRE) == "Treinta y tres" ~ "Treinta y Tres",
            stringr::str_to_sentence(mapa$NOMBRE) == "San jose" ~ "San José",
            TRUE ~ stringr::str_to_sentence(mapa$NOMBRE)
         ),
         ": ",
         formattable::comma(
            x = mapa$ingUSD,
            digits = 0L,
            big.mark = ".",
            decimal.mark = ","
            ),
         " dólares"
         ),
      labelOptions = leaflet::labelOptions(
         style = base::list("font-weight" = "normal", padding = "3px 8px"),
         textsize = "15px",
         direction = "auto"
      )
   )
```

Fuente: elaborado en base a la Encuesta Continua de Hogares del 2018 del INE.
